steps:

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'

    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/new-cloudrun:$COMMIT_SHA', '.']

  # Push the container image to Container Registry

  - name: 'gcr.io/cloud-builders/docker'

    args: ['push', 'gcr.io/$_PROJECT_ID/url-cloud-run:$COMMIT_SHA']

  # Deploy container image to Cloud Run

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'

    entrypoint: gcloud

    args:

    - 'run'

    - 'deploy'

    - 'new-cloudrun'

    - '--image'

    - 'gcr.io/$_PROJECT_ID/new-cloudrun:$COMMIT_SHA'

    - '--region'

    - '$_REGION'

    - '--allow-unauthenticated'




images:

  - 'gcr.io/$_PROJECT_ID/new-cloudrun:$COMMIT_SHA'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET