steps:

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'

    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA', '.']

  # Push the container image to Container Registry

  - name: 'gcr.io/cloud-builders/docker'

    args: ['push', 'gcr.io/$_PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA']

  # Deploy container image to Cloud Run

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'

    entrypoint: gcloud

    args:

  - 'run'

  - 'deploy'

  - 'urlservice'

  - '--image'

  - 'gcr.io/$_PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA'

  - '--region'

  - '$_REGION'

  - '--allow-unauthenticated'

images:

  - 'gcr.io/$_PROJECT_ID/urlservice:$COMMIT_SHA'