---
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$_PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$_PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: null
  - run
  - deploy
  - urlservice
  - --image
  - gcr.io/$_PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA
  - --region
  - $_REGION
  - --allow-unauthenticated
images:
  - gcr.io/$_PROJECT_ID/urlservice:$COMMIT_SHA
